import type { Metadata } from 'next';
import './globals.css';
import { Header, Menu } from '@/app/components';
import TopBar from '@/app/components/client/TopBar/TopBar';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Baptist Union of Moldova',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <TopBar children={<Menu/>}></TopBar>
        <Header/>
        {/*<Menu/>*/}
        <main>{children}</main>
        <h2>Footer</h2>
        </body>
        </html>
    );
}
