import type { Metadata } from 'next';
import './globals.css';
import { ArrowUp, Footer, Header, Menu } from '@/app/components';
import TopBar from '@/app/components/client/TopBar/TopBar';
import AppWrapper from '@/app/context/context';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Baptist Union of Moldova',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <AppWrapper>
            <Header/>
            <TopBar children={<Menu/>}></TopBar>
            <main>{children}</main>
            <Footer/>
            <ArrowUp/>
        </AppWrapper>
        </body>
        </html>
    );
}
